# jekyll config file to exclude some files from being published to github pages
# https://jekyllrb.com/docs/configuration/options/

source: public
destination: .

exclude: 
  - .dockerignore
  - .git
  - Dockerfile
  - LICENSE
  - build.sh
