# jekyll config file to exclude some files from being published to github pages
# https://jekyllrb.com/docs/configuration/options/

source: public
#exclude: 
#  - LICENSE
#  - build.sh
#  - Dockerfile
#  - .dockerignore
